Update contributing guidelines
buchi-labortechnik-ag/contributing pull request #3
Opened 2024-04-05 10:25 UTC by ncudlenco

* Updated the commit types
* Updated the collaborative models for external and internal contributors

2024-04-08 07:59 UTC, Immich requested changes
Good job! I would add a table of contents and take into account the suggestions I made :)

2024-04-08 07:59 UTC, Immich commented on README.md
> +For external collaborators, we are adhering to the [Fork and pull collaboration model]([url](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborat
```suggestion
**For external collaborators**, we are adhering to the [Fork and pull collaboration model]([url](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models#fork-and-pull-model))
```

2024-04-08 07:59 UTC, Immich commented on README.md
> +For internal collaborators we are using the [Shared repository collaboration model]([url](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative
```suggestion
**For internal collaborators**, we are using the [Shared repository collaboration model]([url](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models#shared-repository-model))
```

2024-04-08 08:14 UTC, ncudlenco commented
> Good job! I would add a table of contents and take into account the suggestions I made :)

Done

2024-04-09 14:15 UTC, Immich requested changes

2024-04-09 14:17 UTC, merged